apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pysand-web
spec:
  environments:
    - name: prod
      build:
        from: main
    - name: dev
      build:
        from: dev
  components:
    - name: frontend
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 5000
  dnsAppAlias:
    environment: prod
    component: frontend
