apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pysand-web
spec:
  environments:
    - name: prod
      build:
        from: main
  components:
    - name: frontend
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 5000
      authentication:
        oauth2:
          clientId: c6191833-2675-484e-a855-da1e5b752749
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
    - name: redis
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
  dnsAppAlias:
    environment: prod
    component: frontend
